# Generated by Django 4.2.1 on 2025-07-26 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("linknova", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("url", models.CharField(max_length=4096)),
                ("user_id", models.CharField(db_index=True, max_length=255)),
                ("title", models.CharField(blank=True, max_length=1024, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("referrer", models.CharField(blank=True, max_length=1024, null=True)),
                ("status", models.CharField(max_length=2)),
            ],
            options={
                "db_table": "linknova_bookmark",
            },
        ),
        migrations.CreateModel(
            name="BookmarkCategoryMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bookmark",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="linknova.bookmark",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="linknova.category",
                    ),
                ),
            ],
            options={
                "db_table": "linknova_bookmark_category_map",
                "unique_together": {("category", "bookmark")},
            },
        ),
    ]
