# Generated by Django 4.2.1 on 2024-09-15 14:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("linknova", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            "insert into linknova_topic(name, is_active, created_on, updated_on) values('default', true, now(), now())"
        ),
        migrations.RunSQL(
            "insert into linknova_category(name, topic_id, created_on, updated_on) values('default', (select id from linknova_topic where name = 'default'), now(), now())"
        ),
    ]
