# Generated by Django 4.2.1 on 2024-09-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("linknova", "0002_auto_20240918_1417"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="title",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
